/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Button: typeof import('antd').Button
  const Checkbox: typeof import('antd').Checkbox
  const Col: typeof import('antd').Col
  const DatePicker: typeof import('antd').DatePicker
  const Form: typeof import('antd').Form
  const Fragment: typeof import('react').Fragment
  const Input: typeof import('antd').Input
  const Modal: typeof import('antd').Modal
  const Radio: typeof import('antd').Radio
  const Row: typeof import('antd').Row
  const Select: typeof import('antd').Select
  const Space: typeof import('antd').Space
  const Suspense: typeof import('react').Suspense
  const Switch: typeof import('antd').Switch
  const Table: typeof import('antd').Table
  const Tag: typeof import('antd').Tag
  const Typography: typeof import('antd').Typography
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
